# Generated by Django 2.0.5 on 2018-08-30 11:04

from django.db import migrations, models
import main.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180829_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='image',
            field=models.ImageField(blank=True, upload_to=main.utilities.get_timestamp_path, verbose_name='Изображение'),
        ),
    ]
